#Name of the workflow
name: Example workflow1

#Events that trigger the workflow
on: [push]

#Job definations
jobs:
  hello:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Hello
        run: echo 'Hello world'
